reserveTime/account/urls.py
from django.urls import path
from account.views import *
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views 
from django.urls import reverse_lazy


app_name = 'account'

urlpatterns = [
    path('user/register', CustomerRegisterView.as_view(), name= 'user-register'),
    
    path('login', login_view, name='login'),
    path('logout', LogoutView.as_view(), name = 'logout'),

    path('change_password/',ChangePasswordView.as_view(), name = 'change-password'),
    path('change_password_done/',ChangePasswordDoneView.as_view(), name = 'change-password-done'),

    path("user/<int:pk>", CustomerProfileView.as_view(), name="user-profile"),
    path("user/<int:pk>/update", CustomerUpdateView.as_view(), name="user-update"),

    path("company/<int:pk>", CompanyProfileView.as_view(), name="company-profile"),
    path("company/<int:pk>/update", CompanyUpdateView.as_view(), name="company-update"),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name = 'reset_password.html',
     success_url = reverse_lazy('account:password_reset_done')),
     name="password_reset"),

    path('reset_password_done/', 
        auth_views.PasswordResetDoneView.as_view(template_name = 'reset_password_done.html'), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name = 'password_reset_confirm.html',success_url = reverse_lazy('account:password_reset_complete')), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name = 'password_reset_complete.html'), 
        name="password_reset_complete"),
]



'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
'''

reserveTime/core/api/urls.py
from django.urls import path
from django.conf.urls import include
from rest_framework.urlpatterns import format_suffix_patterns
from core.api.views import UserRegisterView

from core.api.router import router

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('register', UserRegisterView.as_view()), 
]

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
   
]

reserveTime/core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view() , name='home'),
    path("readNotifications/", ReadNotifications.as_view(), name="read-notifications"),
    path("company/profile/<int:pk>", CompanyProfile.as_view(), name="company-profile"),
    path("company/<int:pk>/filter", CommentFilterView.as_view(), name="comment-filter"),
    path("user/<int:pk>/savedRestaurants", SavedRestaurantsView.as_view(), name="user-saved-restaurants"),
    path("companies/<city_location>", CompanyCategoryList.as_view(), name="city-categories"),
    path("companies/<city_location>/filter", CompanyFilterView.as_view(), name="company-filter"),
    path("company_list/<cuisine>", CompanyCuisineListView.as_view(), name="company-cuisine"),
    path("company_list/<cuisine>/filter", CuisineFilterView.as_view(), name="cuisine-filter"),
    path("company/register/compelted", RegisterCompleted.as_view(), name="register-completed"),
    path("reservation/<int:pk>/payment", PaymentView.as_view(), name="payment"),
    path("charge/", charge, name="charge"),
    path("payment/success", SuccessView.as_view(), name="payment-success"),
]

reserveTime/reserveTime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = 'core')),
    path('account/', include(('account.urls', 'django.contrib.auth.urls'))),
    path('company/', include('restaurant.urls', namespace = 'restaurant')),
    path('api/', include('core.api.urls', namespace = 'api')),
    path('api-auth/', include('rest_framework.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reserveTime/restaurant/urls.py
from django.urls import path
from restaurant.views import *

app_name = 'restaurant'

urlpatterns = [
    path('register', RestaurantRegisterView.as_view(), name='company-regsiter'),
    path("menus", MenuView.as_view(), name="menu"),
    path("menus/<int:pk>/update", MenuUpdateView.as_view(), name="menu-update"),
    path("menus/<int:pk>/delete", MenuDeleteView.as_view(), name="menu-delete"),
    path("photos", PhotoView.as_view(), name="photo"),
    path("photos/<int:pk>/update", PhotoUpdateView.as_view(), name="photo-update"),
    path("photos/<int:pk>/delete", PhotoDeleteView.as_view(), name="photo-delete"),
    path("<int:pk>/informations", CompanyInfosView.as_view(), name="company-infos"),
    path("<int:pk>/tables", CompanyTablesView.as_view(), name="company-tables"),
    path("tables/<int:pk>/delete", TableDeleteView.as_view(), name="table-delete"),
    path("<int:pk>/users", ResevedUserList.as_view(), name="company-users"),
    path("<int:pk>/reservations", CompanyReservations.as_view(), name="company-reservations"),
    path("<int:pk>/reviews", CompanyReviews.as_view(), name="company-reviews"),
    path("reservation/<int:pk>", ReservationDetail.as_view(), name="reservation-detail"),
    # path("reservation/<int:pk>", AcceptReservation.as_view(), name='accept-reservation'),
    path("<int:pk>/comment", CommentView.as_view(), name="write-comment")
]

reserveTime/core/models.py
from django.db import models

# Create your models here.

reserveTime/core/forms.py
from django import forms
from account.models import User
from restaurant.models import *

class FindTableForm(forms.Form):

    size = forms.IntegerField( required=True, widget=forms.NumberInput(attrs={
        'id' : 'party-size'
    }))
    date = forms.DateField( required=True, widget=forms.DateInput(attrs={
        'id': 'date',
        'type': 'date'
    }))
    time = forms.TimeField( required=True, widget=forms.TextInput(attrs={
        'type': 'time',
        'id': 'time'
    }))
    

reserveTime/core/api/views.py
from rest_framework import status
from account.models import *
from core.api.serializers import *
                        
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView
from rest_framework import generics
from rest_framework import permissions
from core.api.permissions import IsOwnerOrReadOnly

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework import renderers

from rest_framework import viewsets
from rest_framework.decorators import action

from django.contrib.auth import get_user_model
User = get_user_model()




class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer



class UserRegisterView(CreateAPIView):
    model = User
    serializer_class = RegisterSerializer
    

class CompanyViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Company.objects.all()
    serializer_class = CompanySerializer


class TableViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Table.objects.all()
    serializer_class = TableSerializer

class MenuViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Menu.objects.all()
    serializer_class = MenuSerializer

class MenuCategoryViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = MenuCategory.objects.all()
    serializer_class = MenuCategorySerializer

class PhotoViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Photo.objects.all()
    serializer_class = PhotoSerializer

class CommentViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class ReservationViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Reservation.objects.all()
    serializer_class = ReservationSerializer

class SavedRestaurantViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = SavedRestaurant.objects.all()
    serializer_class = SavedRestaurantSerializer

class PortionViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Portion.objects.all()
    serializer_class = PortionSerializer

class TimeViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Time.objects.all()
    serializer_class = TimeSerializer

reserveTime/core/templates/company-photos.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/user-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/company-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">


    <title>Company Photos</title>

    <style>
        .col{
            padding: 3px;
        }
    </style>

</head>
<body id="company-admin-body">
    
    {% include 'partials/company-header.html' %}
    {% include 'partials/mobile-menu.html' %}

    <main class="full-h">
        <div class="full full-h">
            
            <div class="row full-h  justify-content-center">
                <div class="col-12 col-lg-2 bg-white p-0 admin-menu-col header-shadow">
                    <div class="admin-menu-box mt-5">
                        <nav>
                            <ul class="admin-menu-list">
                                <li>
                                    <a href="{% url 'core:company-profile' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-home"></i>
                                            <span class="ml-2 bold">{{request.user.company.company_name}}</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'account:company-profile' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-cog"></i>
                                            <span class="ml-2 bold">Company Settings</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:photo' %}">
                                        <div class="d-flex">
                                            <i class="fas fa-images"></i>
                                            <span class="ml-2 bold">Photos</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:menu' %}">
                                        <div class="d-flex">
                                            <i class="fas fa-hamburger"></i>
                                            <span class="ml-2 bold">Menus</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:company-infos' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-info-circle"></i>
                                            <span class="ml-2 bold">Informations</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:company-tables' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-table"></i>
                                            <span class="ml-2 bold">Tables</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:company-reservations' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-clock"></i>
                                            <span class="ml-2 bold">Reservations</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:company-users' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-users"></i>
                                            <span class="ml-2 bold">Users</span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-12 col-lg-10">
                    <div class="container mt-3">
                        <div class="row">
                            <h3 class="full bottom-border bold pb-3 mb-5">
                                Add Photo
                            </h3>
                            <form method = "POST" class="add-img-form mt-3 mb-3" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                        <div class="d-flex">
                                            <label for="upload-img" class="add-img-label">Add Photo<i class="ml-2 fas fa-plus-circle"></i></label>
                                            {{form.photo}}
                                            {{form.photo.errors}}
                                        </div>
                                </div>
                                <div class="form-group">
                                    {{form.photo_type}}
                                    {{form.photo_type.errors}}
                                </div>
                                <input type="submit" value="Save" class="save-btn">
                            </form>
                            <h3 class="full bottom-border bold pb-3 mb-5">Company Photos</h3>
                            <div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5 mb-3 full">
                                <!-- <p>You don't have any photo</p> -->
                                {% if photos %}
                                    {% for photo in photos %}
                                            <div class="col">
                                                <a href="{% url 'restaurant:photo-update' photo.pk %}">
                                                    <img class="photo-list-item" src="{{photo.photo.url}}" data-type='{{photo.photo_type}}' alt="">
                                                </a>
                                            </div>
                                    {% endfor %}
                                {% else %}
                                    <p class="bold m-auto">You don't have any photo</p>
                                {% endif %}
                               
                            </div>
            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $(document).ready(function(){
            

            $('.link-box').hover(function(){
                height = $(this).height()
                $(this).stop().animate({
                    borderRadius : '50%',
                    width : height
                    })
            }, function(){
                $(this).animate({
                    borderRadius : '10px',
                    width : '250px'
                    })
            })
        });
    </script>
</body>
</html>

reserveTime/core/templates/cuisine-filter.html
{% load static %}

{% for company in companies %}
    <a href="{% url 'core:company-profile' company.pk %}" class="full">
        <div class="company-item row pt-3 pb-3 mb-5 bottom-border">
            <div class="col-12 col-lg-4 company-profile-img">
                <div class="img-box-container">
                    {% if company.cover_photo %}
                        <img src="{{company.cover_photo.url}}" alt="">
                    {% else %}
                        <img src="{% static 'images/img3.jpg' %}" alt="">
                    {% endif %}
                </div>   
            </div>
            <div class="col-12 col-lg-8">
                <p class="name bold mb-2 pb-2">{{company.company_name}} </p>
                <div class="review-box d-flex mb-2">
                    <div data-type = '{{company.overall}}'  class="stars d-flex rating-box">
                            <div class="star"><i class="far fa-star"></i></div>
                            <div class="star"><i class="far fa-star"></i></div>
                            <div class="star"><i class="far fa-star"></i></div>
                            <div class="star"><i class="far fa-star"></i></div>
                            <div class="star"><i class="far fa-star"></i></div>
                    </div>
                    <p class="review-text ml-2">{{company.company_comment.all.count}} reviews</p>
                </div>
                <div class="d-flex align-items-center mb-3">
                    <p class="location bold">{{company.city_location}}, {{company.country_location}}</p>
                </div>
                <p class="description">
                    {{company.description|slice:":255"}}...</p>
                <div class="d-flex align-items-center">
                    <span class="bold">TakeOut : </span>
                    <div class="ml-3 phone-number d-flex mt-2">
                        <i class="fas fa-phone-alt pr-2"></i> 
                        <p>{{company.phone_number}}</p>
                    </div>
                </div>
            </div>
        </div>
    </a> 
{% endfor %}

reserveTime/core/templates/feedback-email.html
<html>
    <body>
        <div style="width: 100%; height: 400px; background-color: #fff;">
            <div style="width: 400px;
                        height: 100%;
                        margin: auto;">
                <h1 style="width: 100%; text-align: center; font-weight: bold; margin-top: 10px;">Reserve Time</h1>
                <p style="width: 100%; text-align: center; margin-top: 10px; font-weight: bold;">Thank you for your reservation in {{company_name}}</p>
                <a style="background-color: red;
                    text-decoration: none;
                    color: #fff;
                    display: flex;
                    padding: 15px 65px;
                    font-size: 14px;
                    font-weight: bold;
                    border-radius: 10px;
                    margin-top: 25px;"

                href="{{site_address}}{% url 'restaurant:write-comment' company_id %}">Click the link and give us your feedback</a>
            </div>
        </div>
    </body>
</html>

reserveTime/core/templates/menu-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/user-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/company-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <title>Company List</title>

    

</head>
<body id="company-admin-body">
    
    {% include 'partials/company-header.html' %}
    {% include 'partials/mobile-menu.html' %}

    <main class="full-h">
        <div class="full full-h">
            <div class="row full-h justify-content-center">
                <div class="col-3 col-lg-2 bg-white p-0 admin-menu-col header-shadow">
                    <div class="admin-menu-box mt-5">
                        <nav>
                            <ul class="admin-menu-list">
                                <li>
                                    <a href="{% url 'core:company-profile' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-home"></i>
                                            <span class="ml-2 bold">{{request.user.company.company_name}}</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'account:company-profile' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-cogs"></i>
                                            <span class="ml-2 bold">Company Settings</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:photo' %}">
                                        <div class="d-flex">
                                            <i class="fas fa-images"></i>
                                            <span class="ml-2 bold">Photos</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:menu' %}">
                                        <div class="d-flex">
                                            <i class="fas fa-hamburger"></i>
                                            <span class="ml-2 bold">Menus</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:company-infos' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-info-circle"></i>
                                            <span class="ml-2 bold">Informations</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:company-tables' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-table"></i>
                                            <span class="ml-2 bold">Tables</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:company-reservations' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-clock"></i>
                                            <span class="ml-2 bold">Reservations</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'restaurant:company-users' user.company.pk %}">
                                        <div class="d-flex">
                                            <i class="fas fa-users"></i>
                                            <span class="ml-2 bold">Users</span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-9 col-lg-10">
                    <div class="container mt-3">
                        <div class="row">
                            <h3 class="full bottom-border bold pb-3 mb-5">
                                Edit menu
                            </h3>
                            <form class="full mb-3 menu-form" method='POST'>
                            {% csrf_token %}
                               <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="formGroupExampleInput">Title</label>
                                            {{form.title}}
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="selectType">Type</label>
                                            {{form.menu_type}}
                                        </div>
                                    </div>
                                     <div class="col">
                                        <div class="form-group">
                                            <label for="selectType">Price</label>
                                            {{form.price}}
                                        </div>
                                    </div>
                               </div>
                               <div class="row">
                                   <div class="col">
                                        <div class="form-group">
                                            <label for="exampleFormControlTextarea1">Description</label>
                                            {{form.description}}
                                        </div>
                                   </div>
                               </div>  
                                <div class="d-flex justify-content-end">
                                    <input type="submit" value="Save Changes" class="save-btn">
                                    <button type='button' class="delete-btn" data-toggle="modal" data-target="#exampleModal">Delete</button>   
                                </div>  
                            </form>
                            
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Photo</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <p>Are you sure to delete this menu?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
              <form method="POST" action="{% url 'restaurant:menu-delete' menu.pk %}">
                    {% csrf_token %}<input type="submit" class="btn btn-primary" value="DELETE">
              </form>
              
            </div>
          </div>
        </div>
      </div>

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $(document).ready(function(){
        

            $('.link-box').hover(function(){
                height = $(this).height()
                $(this).stop().animate({
                    borderRadius : '50%',
                    width : height
                    })
            }, function(){
                $(this).animate({
                    borderRadius : '10px',
                    width : '250px'
                    })
            })
        });
    </script>
</body>
</html>