reserveTime/account/urls.py
from django.urls import path
from account.views import *
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views 
from django.urls import reverse_lazy


app_name = 'account'

urlpatterns = [
    path('user/register', CustomerRegisterView.as_view(), name= 'user-register'),
    
    path('login', login_view, name='login'),
    path('logout', LogoutView.as_view(), name = 'logout'),

    path('change_password/',ChangePasswordView.as_view(), name = 'change-password'),
    path('change_password_done/',ChangePasswordDoneView.as_view(), name = 'change-password-done'),

    path("user/<int:pk>", CustomerProfileView.as_view(), name="user-profile"),
    path("user/<int:pk>/update", CustomerUpdateView.as_view(), name="user-update"),

    path("company/<int:pk>", CompanyProfileView.as_view(), name="company-profile"),
    path("company/<int:pk>/update", CompanyUpdateView.as_view(), name="company-update"),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name = 'reset_password.html',
     success_url = reverse_lazy('account:password_reset_done')),
     name="password_reset"),

    path('reset_password_done/', 
        auth_views.PasswordResetDoneView.as_view(template_name = 'reset_password_done.html'), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name = 'password_reset_confirm.html',success_url = reverse_lazy('account:password_reset_complete')), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name = 'password_reset_complete.html'), 
        name="password_reset_complete"),
]



'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
'''

reserveTime/core/api/urls.py
from django.urls import path
from django.conf.urls import include
from rest_framework.urlpatterns import format_suffix_patterns
from core.api.views import UserRegisterView

from core.api.router import router

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('register', UserRegisterView.as_view()), 
]

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
   
]

reserveTime/core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view() , name='home'),
    path("readNotifications/", ReadNotifications.as_view(), name="read-notifications"),
    path("company/profile/<int:pk>", CompanyProfile.as_view(), name="company-profile"),
    path("company/<int:pk>/filter", CommentFilterView.as_view(), name="comment-filter"),
    path("user/<int:pk>/savedRestaurants", SavedRestaurantsView.as_view(), name="user-saved-restaurants"),
    path("companies/<city_location>", CompanyCategoryList.as_view(), name="city-categories"),
    path("companies/<city_location>/filter", CompanyFilterView.as_view(), name="company-filter"),
    path("company_list/<cuisine>", CompanyCuisineListView.as_view(), name="company-cuisine"),
    path("company_list/<cuisine>/filter", CuisineFilterView.as_view(), name="cuisine-filter"),
    path("company/register/compelted", RegisterCompleted.as_view(), name="register-completed"),
    path("reservation/<int:pk>/payment", PaymentView.as_view(), name="payment"),
    path("charge/", charge, name="charge"),
    path("payment/success", SuccessView.as_view(), name="payment-success"),
]

reserveTime/reserveTime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = 'core')),
    path('account/', include(('account.urls', 'django.contrib.auth.urls'))),
    path('company/', include('restaurant.urls', namespace = 'restaurant')),
    path('api/', include('core.api.urls', namespace = 'api')),
    path('api-auth/', include('rest_framework.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reserveTime/restaurant/urls.py
from django.urls import path
from restaurant.views import *

app_name = 'restaurant'

urlpatterns = [
    path('register', RestaurantRegisterView.as_view(), name='company-regsiter'),
    path("menus", MenuView.as_view(), name="menu"),
    path("menus/<int:pk>/update", MenuUpdateView.as_view(), name="menu-update"),
    path("menus/<int:pk>/delete", MenuDeleteView.as_view(), name="menu-delete"),
    path("photos", PhotoView.as_view(), name="photo"),
    path("photos/<int:pk>/update", PhotoUpdateView.as_view(), name="photo-update"),
    path("photos/<int:pk>/delete", PhotoDeleteView.as_view(), name="photo-delete"),
    path("<int:pk>/informations", CompanyInfosView.as_view(), name="company-infos"),
    path("<int:pk>/tables", CompanyTablesView.as_view(), name="company-tables"),
    path("tables/<int:pk>/delete", TableDeleteView.as_view(), name="table-delete"),
    path("<int:pk>/users", ResevedUserList.as_view(), name="company-users"),
    path("<int:pk>/reservations", CompanyReservations.as_view(), name="company-reservations"),
    path("<int:pk>/reviews", CompanyReviews.as_view(), name="company-reviews"),
    path("reservation/<int:pk>", ReservationDetail.as_view(), name="reservation-detail"),
    # path("reservation/<int:pk>", AcceptReservation.as_view(), name='accept-reservation'),
    path("<int:pk>/comment", CommentView.as_view(), name="write-comment")
]

reserveTime/core/models.py
from django.db import models

# Create your models here.

reserveTime/core/forms.py
from django import forms
from account.models import User
from restaurant.models import *

class FindTableForm(forms.Form):

    size = forms.IntegerField( required=True, widget=forms.NumberInput(attrs={
        'id' : 'party-size'
    }))
    date = forms.DateField( required=True, widget=forms.DateInput(attrs={
        'id': 'date',
        'type': 'date'
    }))
    time = forms.TimeField( required=True, widget=forms.TextInput(attrs={
        'type': 'time',
        'id': 'time'
    }))
    

reserveTime/core/api/views.py
from rest_framework import status
from account.models import *
from core.api.serializers import *
                        
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView
from rest_framework import generics
from rest_framework import permissions
from core.api.permissions import IsOwnerOrReadOnly

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework import renderers

from rest_framework import viewsets
from rest_framework.decorators import action

from django.contrib.auth import get_user_model
User = get_user_model()




class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer



class UserRegisterView(CreateAPIView):
    model = User
    serializer_class = RegisterSerializer
    

class CompanyViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Company.objects.all()
    serializer_class = CompanySerializer


class TableViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Table.objects.all()
    serializer_class = TableSerializer

class MenuViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Menu.objects.all()
    serializer_class = MenuSerializer

class MenuCategoryViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = MenuCategory.objects.all()
    serializer_class = MenuCategorySerializer

class PhotoViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Photo.objects.all()
    serializer_class = PhotoSerializer

class CommentViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class ReservationViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Reservation.objects.all()
    serializer_class = ReservationSerializer

class SavedRestaurantViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = SavedRestaurant.objects.all()
    serializer_class = SavedRestaurantSerializer

class PortionViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Portion.objects.all()
    serializer_class = PortionSerializer

class TimeViewSet(viewsets.ModelViewSet):
    """
        This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Time.objects.all()
    serializer_class = TimeSerializer

reserveTime/core/templates/partials/company-header.html
{% load static custom_tags %}

<header class="admin-header header-shadow" >
    <div class="container-fluid ">
        <div class="row justify-content-between">
            <div class="left side">
                <button type="button" class="admin-menu-btn">
                    <div class="d-column line-box">
                        <div class="line"></div>
                        <div class="line"></div>
                        <div class="line"></div>
                    </div>
                </button>
                <a href="{% url 'core:home' %}">
                    <img src="{% static 'images/logo.png' %}" class="admin-header-logo" width="230px" alt="">
                </a>
            </div>
            <div class="right side">
                
                <a href="{% url 'account:user-profile' user.pk %}" class="d-flex user-profile-link">
                    <div class="side">
                        {% if user.profile_img %}
                            <img src="{{user.profile_img.url}}" width="70px" height="100%" alt="Profile photo">
                        {% else %}
                            <img src="{% static 'images/profile2.png' %}" width="50px" alt="Profile photo">
                        {% endif %}
                        <div class="d-flex flex-direction-column ml-2 admin-user-box" style="color: #5B5B5B ;">
                            <span class="mt-1">Welcome</span>
                            <h5 class="bold">{{user.first_name}} {{user.last_name}}</h5>
                        </div>
                    </div>
                </a>
                
                {% notification request.user as notifications %} 
                <div class="notification">
                    <button type="button" class="header-btn notification-btn">
                        {% if notifications %}
                            <span class="notification-count" style="top:28px;"></span>
                        {% endif %}
                        <i class="far fa-bell"></i>
                    </button>
                    <div class="custom-drop-down box3 scroll-y p-3 shadow" style="display: none;">
                        <div class="triangle"></div>
                        <span>Notifications</span>
                        {% if notifications %}
                            {% for notification in notifications %}
                                {% if notification.notification_type == 'new_reservation' %}
                                    <a class="pl-2 pr-2" href="{% url 'restaurant:company-reservations' user.company.pk %}">
                                        <div class="d-flex align-items-center">
                                            <i class="far fa-clock mr-3"></i>
                                            <div class="d-column">
                                                {{notification.text}}
                                                <small>From {{notification.sender.email}}</small>   
                                            </div>
                                        </div>
                                    </a>
                                {% elif notification.notification_type == 'accept_reservation' %}
                                    <a class="pl-2 pr-2 mb-2 d-column" href="{% url 'account:user-profile' request.user.pk %}">
                                        <div class="d-flex align-items-center">
                                            <i class="far fa-calendar-check mr-3"></i>
                                            <div class="d-column">
                                                {{notification.text}}
                                                <small>By {{notification.sender.company.company_name}}</small>   
                                            </div>
                                        </div>
                                        
                                    </a>
                                {% endif %}
                            {% endfor %}

                            <form  class="full mt-2 mb-2" id="readNotifications" action="{% url 'core:read-notifications' %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-outline-secondary float-r" value="Mark all as read!">
                            </form>
                        {% else %}
                            <img src="{% static 'images/animat-bell-color.gif' %}" width="50%" class="m-auto" alt="">
                            <p class="pl-2 pr-2 bold text-center">Nothing to see here, you’re all caught up!</p>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
        </div>
        
    </div>
   
</header>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script>
    $('#readNotifications').on('submit', function(e){
        e.preventDefault()  
        
        $.ajax({
            type: "POST",
            url: $('#readNotifications').attr('action'),
            data:  {
                csrfmiddlewaretoken:$('#readNotifications').find('input[name=csrfmiddlewaretoken]').val(),
                form_id : $('#readNotifications').attr('id')
            },
            dataType: 'json',
            success: function (data) {
                console.log(data);
            },
            error: function(data) {
                alert("error");
                console.log(data);
            }
        });
    });
</script>

reserveTime/core/templates/partials/header.html
{% load static custom_tags %}
<style>
    header .side{
        margin: 5px 0;
    }
</style>
<header >
    <div class="container custom-container shadow">
        <div class="row justify-content-between">
            <div class="left side">
                <a href="{% url 'core:home' %}">
                    <img src="{% static 'images/logo.png' %}" width="200px" alt="">
                </a>
            </div>
            <div class="right side">
                
                {% if request.user.is_authenticated %}
                    <div class="user-profile border-right pr-2">
                        <span class="header-btn" style="cursor:pointer;"> Hi, {{request.user.first_name|capfirst}} <i class="fas fa-chevron-down" id="arrow-down"></i></span>
                        <div class="custom-drop-down shadow box1" style="display: none;">
                            <div class="triangle"></div>
                            <!-- <span>Hello, {{request.user.first_name|capfirst}}</span> -->
                            <ul>
                                {% if request.user.is_company %}
                                    <li><a href="{% url 'core:company-profile' user.company.pk %}">
                                        <i class="fas fa-home mr-2"></i>
                                        {{request.user.company.company_name}}</a></li>
                                    <li><a href="{% url 'account:company-profile' user.pk %}">
                                        <i class="fas fa-cog mr-2"></i>
                                        Company Settings</a></li>
                                    <li><a href="{% url 'account:user-profile' user.pk %}">
                                        <i class="far fa-user-circle mr-2"></i>
                                        My Profile</a></li>
                                {% else %}
                                    <li><a href="{% url 'account:user-profile' user.pk %}">
                                        <i class="far fa-user-circle mr-2"></i>
                                        My Profile</a></li>
                                {% endif %}
                                <li><a href="{% url 'account:user-profile' user.pk %}">
                                    <i class="fas fa-history mr-2"></i>
                                    My Dining History</a></li>
                                <li><a href="{% url 'core:user-saved-restaurants' user.pk %}">
                                    <i class="fas fa-bookmark mr-2"></i>
                                    My Saved Restaurants</a></li>
                                <li><a href="{% url 'account:logout' %} " style="color: red;">
                                    <i class="fas fa-sign-out-alt mr-2"  style="color: red;"></i>
                                    Sign out</a></li>
                            </ul>
                        </div>
                    </div>
                    {% reservation request.user as reservations%}
                    <div class="reserve-table">
                        <button type="button" class="header-btn"><i class="far fa-calendar"></i></button>
                        <div class="custom-drop-down p-3 scroll-y shadow box2" style="display: none;">
                            <div class="triangle"></div>
                            <span class="pb-2">Upcoming reservations</span>
                            {% if reservations %}
                                {% for reservation in reservations %}
                                    <div class="card mb-3" style="max-width: 540px;">
                                        <div class="row no-gutters">
                                        <div class="col-md-4">
                                            {% if reservation.company.cover_photo %}
                                                <img src="{{reservation.company.cover_photo.url}}" class="card-img" style="width: 100px;height: 100px; object-fit: cover;">
                                            {% else %}
                                                <img src="{% static 'images/img3.jpg' %}" class="card-img" style="width: 100px;height: 100px; object-fit: cover;">
                                            {% endif %}
                                        </div>
                                        <div class="col-md-8">
                                            <div class="card-body">
                                                <h5 class="card-title">{{reservation.company.company_name}}</h5>
                                                <p class="card-text">{{reservation.reserved_date}}, {{reservation.reserved_time}}</p>
                                                <p class="card-text"><small class="text-muted">{{reservation.company.city_location}}, {{reservation.company.province_location}}</small></p>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                    
                                {% endfor %}
                            {% else %}
                                <p class="pl-2 pr-2">You have no upcoming reservations</p>
                            {% endif %}
                        </div>
                    </div>
                    {% notification request.user as notifications %} 
                    <div class="notification">
                        <button type="button" class="header-btn notification-btn">
                            {% if notifications %}
                                <span class="notification-count"></span>
                            {% endif %}
                            <i class="far fa-bell"></i>
                        </button>
                        <div class="custom-drop-down box3 scroll-y p-3 shadow" style="display: none;">
                            <div class="triangle"></div>
                            <span>Notifications</span>
                            {% if notifications %}
                                {% for notification in notifications %}
                                    {% if notification.notification_type == 'new_reservation' %}
                                        <a class="pl-2 pr-2" href="{% url 'restaurant:company-reservations' user.company.pk %}">
                                            <div class="d-flex align-items-center">
                                                <i class="far fa-clock mr-3"></i>
                                                <div class="d-column">
                                                    {{notification.text}}
                                                    <small>From {{notification.sender.email}}</small>   
                                                </div>
                                            </div>
                                        </a>
                                    {% elif notification.notification_type == 'accept_reservation' %}
                                        <a class="pl-2 pr-2 mb-2 d-column" href="{% url 'account:user-profile' request.user.pk %}">
                                            <div class="d-flex align-items-center">
                                                <i class="far fa-calendar-check mr-3"></i>
                                                <div class="d-column">
                                                    {{notification.text}}
                                                    <small>By {{notification.sender.company.company_name}}</small>   
                                                </div>
                                            </div>
                                            
                                        </a>
                                    {% endif %}
                                {% endfor %}

                                <form  class="full mt-2 mb-2" id="readNotifications" action="{% url 'core:read-notifications' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-outline-secondary float-r" value="Mark all as read!">
                                </form>
                            {% else %}
                                <img src="{% static 'images/animat-bell-color.gif' %}" width="50%" class="m-auto" alt="">
                                <p class="pl-2 pr-2 bold text-center">Nothing to see here, you’re all caught up!</p>
                            {% endif %}
                            
                        </div>
                    </div>
                {% else %}
                    <button type="button" class="btn register-btn mr-2" data-toggle="modal" data-target="#exampleModal">Sign Up</button>
                    <a href="{% url 'account:login' %}" class="btn login-btn bold">Sign In</a>
                {% endif %}
                
               
            </div>
        </div>
        
    </div>
    
</header>
<section>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sign Up</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body d-column">
                <a href="{% url 'account:user-register' %}" class="btn register-btn mb-2">Sign Up for User</a>
                <a href="{% url 'restaurant:company-regsiter' %}" class="btn register-btn">Sign Up for Company</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script>
    $('#readNotifications').on('submit', function(e){
        e.preventDefault()  
        
        $.ajax({
            type: "POST",
            url: $('#readNotifications').attr('action'),
            data:  {
                csrfmiddlewaretoken:$('#readNotifications').find('input[name=csrfmiddlewaretoken]').val(),
                form_id : $('#readNotifications').attr('id')
            },
            dataType: 'json',
            success: function (data) {
                console.log(data);
            },
            error: function(data) {
                alert("error");
                console.log(data);
            }
        });
    });
</script>

reserveTime/core/templates/partials/mobile-menu.html
<div class="menu-box-left" style="display: none;"></div>
    <div class="menu-box-in pt-3" style="display: none;">
        <div class="menu-box-in-body">
            <div>
                <ul class="admin-menu-list">
                    <li>
                        <a href="{% url 'core:company-profile' user.company.pk %}">
                            <div class="d-flex">
                                <i class="fas fa-home"></i>
                                <span class="ml-2 bold">{{request.user.company.company_name}}</span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'account:company-profile' user.company.pk %}">
                            <div class="d-flex">
                                <i class="fas fa-cog"></i>
                                <span class="ml-2 bold">Company Settings</span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'restaurant:photo' %}">
                            <div class="d-flex">
                                <i class="fas fa-images"></i>
                                <span class="ml-2 bold">Photos</span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'restaurant:menu' %}">
                            <div class="d-flex">
                                <i class="fas fa-hamburger"></i>
                                <span class="ml-2 bold">Menus</span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'restaurant:company-infos' user.company.pk %}">
                            <div class="d-flex">
                                <i class="fas fa-info-circle"></i>
                                <span class="ml-2 bold">Informations</span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'restaurant:company-tables' user.company.pk %}">
                            <div class="d-flex">
                                <i class="fas fa-table"></i>
                                <span class="ml-2 bold">Tables</span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'restaurant:company-reservations' user.company.pk %}">
                            <div class="d-flex">
                                <i class="fas fa-clock"></i>
                                <span class="ml-2 bold">Reservations</span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'restaurant:company-users' user.company.pk %}">
                            <div class="d-flex">
                                <i class="fas fa-users"></i>
                                <span class="ml-2 bold">Users</span>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>