reserveTime/account/urls.py
from django.urls import path
from account.views import *
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views 
from django.urls import reverse_lazy


app_name = 'account'

urlpatterns = [
    path('user/register', CustomerRegisterView.as_view(), name= 'user-register'),
    
    path('login', login_view, name='login'),
    path('logout', LogoutView.as_view(), name = 'logout'),

    path('change_password/',ChangePasswordView.as_view(), name = 'change-password'),
    path('change_password_done/',ChangePasswordDoneView.as_view(), name = 'change-password-done'),

    path("user/<int:pk>", CustomerProfileView.as_view(), name="user-profile"),
    path("user/<int:pk>/update", CustomerUpdateView.as_view(), name="user-update"),

    path("company/<int:pk>", CompanyProfileView.as_view(), name="company-profile"),
    path("company/<int:pk>/update", CompanyUpdateView.as_view(), name="company-update"),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name = 'reset_password.html',
     success_url = reverse_lazy('account:password_reset_done')),
     name="password_reset"),

    path('reset_password_done/', 
        auth_views.PasswordResetDoneView.as_view(template_name = 'reset_password_done.html'), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name = 'password_reset_confirm.html',success_url = reverse_lazy('account:password_reset_complete')), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name = 'password_reset_complete.html'), 
        name="password_reset_complete"),
]



'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
'''

reserveTime/core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view() , name='home'),
    path("readNotifications/", ReadNotifications.as_view(), name="read-notifications"),
    path("company/profile/<int:pk>", CompanyProfile.as_view(), name="company-profile"),
    path("company/<int:pk>/filter", CommentFilterView.as_view(), name="comment-filter"),
    path("user/<int:pk>/savedRestaurants", SavedRestaurantsView.as_view(), name="user-saved-restaurants"),
    path("companies/<city_location>", CompanyCategoryList.as_view(), name="city-categories"),
    path("companies/<city_location>/filter", CompanyFilterView.as_view(), name="company-filter"),
    path("company_list/<cuisine>", CompanyCuisineListView.as_view(), name="company-cuisine"),
    path("company_list/<cuisine>/filter", CuisineFilterView.as_view(), name="cuisine-filter"),
    path("company/register/compelted", RegisterCompleted.as_view(), name="register-completed"),
    path("reservation/<int:pk>/payment", PaymentView.as_view(), name="payment"),
    path("charge/", charge, name="charge"),
    path("payment/success", SuccessView.as_view(), name="payment-success"),
]

reserveTime/reserveTime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = 'core')),
    path('account/', include(('account.urls', 'django.contrib.auth.urls'))),
    path('company/', include('restaurant.urls', namespace = 'restaurant')),
    path('api/', include('core.api.urls', namespace = 'api')),
    path('api-auth/', include('rest_framework.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reserveTime/account/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, AbstractUser
from django.utils.translation import ugettext_lazy as _

from restaurant.models import Company
from account.managers import UserManager


class User(AbstractUser):
    is_customer = models.BooleanField(default=False)
    is_company = models.BooleanField(default=False)
    
    email = models.EmailField(_("Email"), max_length=254, unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    profile_img = models.ImageField(_("Profile image"),upload_to='profile-pictures/', null=True, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'    
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email



class Customer(models.Model):
    user = models.OneToOneField("account.User", verbose_name=_("customer"), on_delete=models.CASCADE, primary_key=True, related_name='customer')
    
    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'

    def __str__(self):
        return self.user.email
    

reserveTime/account/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django import forms
from django.db import transaction
from .models import User,Company,Customer

class CustomerRegisterForm(UserCreationForm):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={
                    'class': 'form-control height',
                    'placeholder' : 'First Name *',
                }))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={
                    'class': 'form-control height',
                    'placeholder' : 'Last Name *',
                }))
    username = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
                    'class': 'form-control height',
                    'placeholder' : 'Email *',
                }))
    password1 = forms.CharField(required=True, widget = forms.PasswordInput(attrs={
                    'class': 'form-control height',
                    'placeholder' : 'Password *',
                }))
    password2 = forms.CharField(required=True, widget = forms.PasswordInput(attrs={
                    'class': 'form-control height',
                    'placeholder' : 'Re-enter Password *',
                }))
                
    # profile_image = forms.FileField('Profile', max_length=, required=False)

    class Meta(UserCreationForm.Meta):
        model = User
        
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.is_active = True
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.email = self.cleaned_data.get('username')
        user.save()
        customer = Customer.objects.create(user=user)
        customer.phone_number=self.cleaned_data.get('phone_number')
        # customer.location=self.cleaned_data.get('location')
        customer.save()
        return user


class RestaurantRegisterForm(UserCreationForm):
    password1 = forms.CharField(required=True, widget = forms.PasswordInput(attrs={
                    'class': 'form-control register-input',
                    
                }), label = 'Password')
    password2 = forms.CharField(required=True, widget = forms.PasswordInput(attrs={
                    'class': 'form-control register-input',
                    
                }), label = 'Confirm Password')
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={
                    'class': 'form-control register-input',
                }))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={
                    'class': 'form-control register-input',
                }))
    username = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
                    'class': 'form-control register-input',
                }), label='Email Address')

    company_name = forms.CharField(max_length=250, widget=forms.TextInput(attrs={
                    'class': 'form-control register-input',
                }))
    phone_number = forms.CharField(required=True, widget=forms.TextInput(attrs={
                    'class': 'form-control register-input',
                }))

    city_location = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
                    'class': 'form-control register-input',
                }))
    province_location = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
                    'class': 'form-control register-input',
                }))
    country_location = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
                    'class': 'form-control register-input',
                }))

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_company = True
        user.is_active = False
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.email = self.cleaned_data.get('username')
        user.save()
        company = Company.objects.create(user=user)
        company.phone_number=self.cleaned_data['phone_number']
        company.company_name=self.cleaned_data['company_name']
        company.city_location=self.cleaned_data['city_location']
        company.province_location=self.cleaned_data['province_location']
        company.country_location=self.cleaned_data['country_location']
        company.save()
        return user
 
  
class LoginForm(forms.Form):
    username = forms.EmailField(widget = forms.EmailInput(attrs = {
        'placeholder' : 'Email',
        'class' : 'form-control',
    }))
    password = forms.CharField(widget = forms.PasswordInput(attrs = {
        'placeholder' : 'Password',
        'class' : 'form-control',
    }))


class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
        'placeholder' : 'Old password'
    }), required=True)

    new_password1 = forms.CharField(widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
        'placeholder' : 'New password'
    }), required=True)

    new_password2 = forms.CharField(widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
        'placeholder' : 'Re-enter new password'
    }), required=True)
    
    
class UserEditForm(forms.ModelForm):
    # profile_img = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = User
        fields = ['first_name', 'last_name','email','profile_img']

        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control height mb-4',
                'placeholder' : 'First Name',
                }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control height mb-4',
                'placeholder' : 'Last Name',
                }),
            'email' : forms.EmailInput(attrs = {
                'class' : 'form-control height mb-4',
                'placeholder' : 'Email'
            })
        }

reserveTime/account/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.views.generic import DetailView, UpdateView
from account.models import *
from account.forms import *
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView,PasswordChangeView,PasswordChangeDoneView,PasswordResetView, PasswordResetConfirmView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from restaurant.models import *
from django.db.models import Sum, Avg
import datetime


class CustomerRegisterView(CreateView):
    model = User
    form_class = CustomerRegisterForm
    template_name = 'register-user.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'customer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        # login(self.request, user)
        return redirect('core:home')



def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST or None)
        email = request.POST['username']
        password = request.POST['password']
        user = authenticate(email=email, password=password)

        if user is not None:
            if user.is_active:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('core:home')
        else:
            messages.error(request,'Email or password is not correct')
            return redirect('account:login')

    else:
        form = LoginForm()
    return render(request, 'login-user.html', {'form': form})




class ChangePasswordView(PasswordChangeView):
    template_name = 'change-password.html'
    form_class = ChangePasswordForm
    success_url = reverse_lazy('core:home')


class ChangePasswordDoneView(PasswordChangeDoneView):
    template_name = 'change_password_done.html'


class CustomerProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user-profile.html'
    context_opject_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        upcoming_reservations = Reservation.objects.filter(user=self.request.user, accept=True, reserved_date__gte=datetime.datetime.today())
        past_reservations = Reservation.objects.filter(user=self.request.user, accept=True, reserved_date__lt=datetime.datetime.today())

        context["upcoming_reservations"] = upcoming_reservations
        context["past_reservations"] = past_reservations
        
        return context

    def get_object(self):
        return self.request.user


class CustomerUpdateView(UpdateView):
    model = User
    form_class = UserEditForm
    template_name = 'user-edit.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('account:user-profile', kwargs={'pk': self.object.pk})


class CompanyProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'company-admin-page.html'
    context_opject_name = 'user'

    def get_object(self):
        return self.request.user
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        company = Company.objects.filter(pk=self.kwargs.get('pk'))
        comments = Comment.objects.filter(company = company.first())

        food = comments.aggregate(Avg('ratingFood'))
        service = comments.aggregate(Avg('ratingService'))
        ambience = comments.aggregate(Avg('ratingAmbience'))

        reservations = Reservation.objects.filter(company__in=company)

        all_reserved_user_list = []
        check_user_list = []
        
        for reservation in reservations:
            if reservation.user not in check_user_list:
                reserved_user_obj = {
                    'user' : reservation.user,
                    'reservation_count' : reservations.filter(user = reservation.user).count(),
                    'total_price' : reservations.filter(user = reservation.user).aggregate(Sum('total_price')).get('total_price__sum' , 0),
                    'last_reserved_date' : reservations.filter(user = reservation.user).last().reserved_date,
                    'reviews' : reservation.user.user_comment.all().count()
                }
                all_reserved_user_list.append(reserved_user_obj)
            check_user_list.append(reservation.user)

        context['reserved_users_count'] = len(all_reserved_user_list)
        

        if food.get('ratingFood__avg', 0) and service.get('ratingService__avg', 0) and ambience.get('ratingAmbience__avg', 0)   :
            print('ok')
            context['food_avg'] = "{:.1f}".format(food.get('ratingFood__avg', 0))

            context['service_avg'] = "{:.1f}".format(service.get('ratingService__avg', 0))

            context['ambience_avg'] = "{:.1f}".format(ambience.get('ratingAmbience__avg', 0))

        return context
    


class CompanyUpdateView(UpdateView):
    model = User
    form_class = UserEditForm
    template_name = 'user-edit.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('account:company-profile', kwargs={'pk': self.object.pk})

reserveTime/account/templates/change-password.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="http:////netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/user-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/company-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/reserve-page.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <title>User Login</title>
</head>
<body id="profile-body">
    
    {% include 'partials/header.html' %}
    
    <!-- <main class="mb-5"> -->
        <div class="container main-register-container pb-5">
            <div class="row">
                <div class="col-lg-5 mx-auto pt-5">
                    <form method = "POST">
                        {% csrf_token %}
                        {{form}}
                        <div class="form-group form-check">
                          <input type="checkbox" class="form-check-input" id="exampleCheck1">
                          <label class="form-check-label" for="exampleCheck1">Remember me</label>
                          <a href="" class="float-right">Forgot password?</a>
                        </div>
                        <div class="form-group" style="text-align: center;">
                            <input type="submit" value="Change" class="btn btn-danger px-5 register-user-btn" >
                        </div>
                    </form>
                </div>
               
            </div>
        
        </div>
    <!-- </main> -->
    

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $(document).ready(function(){
        
            $('.show-menu-btn').click(function(){
                $('.menu-container').toggleClass('collapse-menu')
                
                if ($(this).text() == 'Show full menu') {
                    $(this).text('Collapse Menu')
                }
                else{
                    $(this).text('Show full menu')
                }
            });
        });
    </script>
</body>
</html>

reserveTime/account/templates/user-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static custom_tags %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/user-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/company-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

    <title>My Profile</title>
    
    <style>
        .custom-container{
            background-color: transparent;
        }
    </style>

</head>
<body id="profile-body">
    {% include 'partials/header.html' %}

    <div class="container custom-container bg-white shadow border-top">
        <div class="row username-box">  
            {% if user.profile_img %}
                <a data-fancybox="gallery" href="{{user.profile_img.url}}"><img src="{{user.profile_img.url}}"></a>
            {% else %}
                <img src="{% static 'images/profile.png' %}" alt="">
            {% endif %}
            <div>
                <h2> {{user.first_name|capfirst}} {{user.last_name|capfirst}} </h2>
                <span>0 points</span>
            </div>
        </div>
    </div>

    <main class="mb-5 mt-3">
        <div class="container custom-container">
            <div class="inner-container">
                <div class="row">
                    <div class="col-lg-2">
                        <nav>
                            <ul class="profile-menu-list">
                                <li><a href="{% url 'core:user-saved-restaurants' user.pk %}">Saved Restaurants</a></li>
                                <li><a href="{% url 'account:user-update' user.pk %}">Account Details</a></li>
                                <li><a href="#">Delete Account</a></li>
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-10">
                        <div class="reservations">
                            <div class="name">
                                <h3>Upcoming Reservations</h3>
                            </div>
                            <div class="content">
                                {% if upcoming_reservations %}
                                    {% for reservation in upcoming_reservations %}
                                        <div class="company-item row pt-3 pb-3 mb-4 bottom-border">
                                            <div class="col-3 company-profile-img">
                                                {% if reservation.company.cover_photo %}
                                                    <img src="{{ reservation.company.cover_photo.url }}" alt="">
                                                {% else %}
                                                    <img src="{% static 'images/img3.jpg' %}" alt="">
                                                {% endif %}
                                            </div>
                                            <div class="col-9">
                                                <div class="d-flex ">
                                                    <span class="mb-3" style="font-size: 25px;">{{reservation.company.company_name}} </span>
                                                </div>
                                                <div class="d-flex ">
                                                    <span class="bold mr-2">Reserve Date and Time : </span>
                                                    <p>{{reservation.reserved_date}}, {{reservation.reserved_time|time:'H:i:s'}}</p>
                                                </div>
                                                {% get_party_size reservation.table_id as party_size %}
                                                <div class="d-flex">
                                                    <span class="bold mr-2">Party Size : </span>
                                                    <p> {{party_size}}</p>
                                                </div> 
                                                <div class="d-flex">
                                                    <span class="bold mr-2">Total Price : </span>
                                                    <p> {{reservation.total_price}} $</p>
                                                </div> 
                                                <div class="d-flex align-items-center">
                                                    <span class="bold mr-2">Location : </span>
                                                    <p class="location">{{reservation.company.city_location}}, {{reservation.company.province_location}}</p>
                                                </div>
                                                <div class="d-flex align-items-center mt-2">
                                                    <span>TakeOut : </span>
                                                    <div class="ml-3 phone-number d-flex">
                                                        <i class="fas fa-phone-alt pr-2"></i>
                                                        {% if reservation.company.phone_number %}
                                                            <p>{{reservation.company.phone_number}}</p>
                                                        {% else %}
                                                            <p>xxx xxx xx xx</p>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}   
                                {% else %}
                                   <p>No Upcoming Reservations <a href="{% url 'core:home' %}">Book a Table</a>.</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="reservations">
                            <div class="name">
                                <h3>Past Reservations</h3>
                            </div>
                            <div class="content">
                                {% if past_reservations %}
                                    {% for reservation in past_reservations %}
                                        <div class="company-item row pt-3 pb-3 mb-4 bottom-border">
                                            <div class="col-3 company-profile-img">
                                                {% if reservation.company.cover_photo %}
                                                    <img src="{{ reservation.company.cover_photo.url }}" alt="">
                                                {% else %}
                                                    <img src="{% static 'images/img3.jpg' %}" alt="">
                                                {% endif %}
                                            </div>
                                            <div class="col-9">
                                                <div class="d-flex ">
                                                    <span class="mb-3" style="font-size: 25px;">{{reservation.company.company_name}} </span>
                                                </div>
                                                <div class="d-flex ">
                                                    <span class="bold mr-2">Reserve Date and Time : </span>
                                                    <p>{{reservation.reserved_date}}, {{reservation.reserved_time|time:'H:i:s'}}</p>
                                                </div>
                                                <div class="d-flex">
                                                    <span class="bold mr-2">Total Price : </span>
                                                    <p> {{reservation.total_price}} $</p>
                                                </div>

                                                <div class="d-flex align-items-center">
                                                    <span class="bold mr-2">Location : </span>
                                                    <p class="location">{{reservation.company.country_location}}, {{reservation.company.city_location}}</p>
                                                </div>
                                                <div class="d-flex align-items-center mt-2">
                                                    <span>TakeOut : </span>
                                                    <div class="ml-3 phone-number d-flex">
                                                        <i class="fas fa-phone-alt pr-2"></i>
                                                        {% if reservation.company.phone_number %}
                                                            <p>{{reservation.company.phone_number}}</p>
                                                        {% else %}
                                                            <p>xxx xxx xx xx</p>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}   
                                {% else %}
                                   <p>No Past Reservations</p>
                                {% endif %}
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </main>
    
    {% include 'partials/footer.html' %}


    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    
</body>
</html>